#!/usr/bin/env bash

#===============================================================================================
# COMMAND LINE OPTIONS
#===============================================================================================

# Global Variables
source ./lib/globals

#-----------------------------------------------------------------------------------------------
# HELPER FUNCTIONS

# Handle CLI Arguments
handle_arguments() {
    # Set Additional Defaults
    if [ $# -ne 0 ]; then
        BREW_FILE=${1}
        echo "Using Brewfile '${BREW_FILE}'"
    fi
}

# Bash Builtin Getopts
handle_getopts() {
    OPTIONS=":EFhi:s"

    # No Arguments Runs FULL Install
    if [ $# -eq 0 ]; then
        RUN_SECONDARY=true
    fi

    # Handle Options
    while getopts ${OPTIONS} option; do
        case "${option}" in
        E)
            SETUP_MODE="ESSENTIALS"
            ;;
        F)
            # Global Default: SETUP_MODE="FULL"
            RUN_SECONDARY=true
            ;;
        i)
            SETUP_MODE=$(echo ${OPTARG} | tr [:lower:] [:upper:])
            case "${SETUP_MODE}" in
                FULL)
                    # Global Default: SETUP_MODE="FULL"
                    RUN_SECONDARY=true
                    ;;
                ESSENTIALS)
                    ;;
                *)
                    echo "Incorrect option provided for -i: ${OPTARG}"
                    usage
                    ;;
            esac
            ;;
        s)
            RUN_SECONDARY=true
            ;;
        \?)
            echo "Invalid Option: -${OPTARG}"
            usage
            ;;
        :)
            echo "Invalid Option: -${OPTARG} requires an argument"
            usage
            ;;
        h | *)
            usage
            ;;
        esac
    done

    shift $((OPTIND -1)) # remove options already handled by getopts from $@

    handle_arguments "$@"
}

# Prettify Options Output Message
print_option() {
    printf "\t%s\t%s\n" "${1}" "${2}" | expand -t 4,28
}

# Usage Message
usage() {
    echo -e "\nUsage: $(basename "$0") [Options] Brewfile\n"
    echo -e "\nRunning install without any options below will run a FULL setup by default.\n"
    echo -e "\nOptions:\n"
    print_option "-F" "Full install setup (Defaults: -s=true)"
    print_option "-E" "Essentials only installations"
    print_option "-i [full|essentials]" "More explicit install type declaration"
    print_option "-s" "Run secondary installation (Default: false)"
    print_option "-h" "Prints this usage message"
    echo -e "\nArguments:\n"
    print_option "Brewfile" "Path to Brew bundle file (Default: '${BREW_FILE}')"
    echo -e "\n"
    1>&2
    exit 1
}
