#!/usr/bin/env bash

#===============================================================================================
# GLOBAL ENVIRONMENT VARIABLES
#===============================================================================================

# General
ADMIN=$(dsmemberutil checkmembership -U $(whoami) -G admin | grep "not")
DEFAULTS=false
ICLOUD_HOME_PATH="~/Library/Mobile\ Documents/com~apple~CloudDocs"
RESTORE_BACKUP=false
RUN_SECONDARY=false
SECONDARY_FILE="./secondary.sh"
SET_DEFAULT_SYSTEM_PREFERENCES=false
SETUP_TYPE="MAIN"  # DEFAULT: Main setup - installs everything in Brewfile and secondary.sh
USER_NAME=$(id -F) # Complete user's name, e.g. Andrés Bretón

# Setup File Paths
SOURCE_PATH="./src/"
BREW_CASKS_FILE="${SOURCE_PATH}casks.txt"
BREW_FILE="${SOURCE_PATH}Brewfile"
BREW_FORMULAE_FILE="${SOURCE_PATH}formulae.txt"
BREW_TAPS_FILE="${SOURCE_PATH}taps.txt"
ESSENTIALS_BREW_FILE="${SOURCE_PATH}essentials/Brewfile"
ESSENTIALS_INSTALL_FILE="${SOURCE_PATH}essentials/install.sh"
MAC_APPS_FILE="${SOURCE_PATH}apps.txt"

# Shell Defaults
CURRENT_SHELL=$(echo $0)
DEFAULT_SHELL=$(echo ${SHELL##*/})
BASH_PROFILE_FILE=".bash_profile"
BASH_RC_FILE=".bashrc"
ZSH_PROFILE_FILE=".zprofile"
ZSH_RC_FILE=".zshrc"

BASH_PROFILE_PATH="${HOME}/${BASH_PROFILE_FILE}"
BASH_RC_PATH="${HOME}/${BASH_RC_FILE}"
ZSH_PROFILE_PATH="${HOME}/${ZSH_PROFILE_FILE}"
ZSH_RC_PATH="${HOME}/${ZSH_RC_FILE}"
SHELL_PROFILE_FILE="${ZSH_PROFILE_PATH}"

# macOS Version
IS_APPLE_CPU=$(sysctl -n machdep.cpu.brand_string | grep -i "apple") # Apple M1 Hardware = "Apple processor"
MAC_OS_VERSION=$(sw_vers -productVersion)
OS_MAJOR_VERSION=$(echo $MAC_OS_VERSION | sed -E 's/([0-9]+)\.[0-9]+\.[0-9]+/\1/')
OS_MINOR_VERSION=$(echo $MAC_OS_VERSION | sed -E 's/[0-9]+\.([0-9]+)\.[0-9]+/\1/')
if [ ${OS_MAJOR_VERSION} -ge 11 ]; then
    IS_BIG_SUR=true
elif [ ${OS_MAJOR_VERSION} -eq 10 ]; then
    if [ ${OS_MINOR_VERSION} -gt 14 ]; then
        IS_CATALINA=true # 15 (Catalina)
    elif [ ${OS_MINOR_VERSION} -eq 14 ]; then
        IS_CATALINA=false # 14 (Mojave)
        DEFAULT_SHELL="bash"
        SHELL_PROFILE_FILE="${BASH_PROFILE_PATH}"
    else
        OS_UNSUPPORTED=true
    fi
else
    OS_UNSUPPORTED=true
fi

# Shell Defaults
# ! Order is important - determined by macOS version above
SHELL_RC_FILE="${HOME}/.${DEFAULT_SHELL}rc"

# Setup Configuration Variables
GITHUB_KEYS_URL="https://github.com/settings/keys"
GITHUB_RSA_NAME="github_rsa"

# Color Outputs
GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
NC="\033[0m"

# Emojis UTF-8 Hex
EMOJI_BEER="\xf0\x9f\x8d\xba\x20"
EMOJI_CHECKMARK="\xe2\x9c\x85\x20"
EMOJI_ERROR="\xe2\x9b\x94\xef\xb8\x8f\x20"
EMOJI_FAIL="\xe2\x9d\x8c\x20"
EMOJI_GEAR="\xe2\x9a\x99\xef\xb8\x8f\x20\x20"
EMOJI_INFO="\xe2\x84\xb9\xef\xb8\x8f\x20\x20"
EMOJI_STOP="\xf0\x9f\x9b\x91\x20"
EMOJI_TRASH="\xf0\x9f\x97\x91\x20\x20"
EMOJI_TOOLBOX="\xf0\x9f\xa7\xb0\x20"
EMOJI_WARNING="\xe2\x9b\x94\xef\xb8\x8f\x20"
EMOJI_WRENCH="\xf0\x9f\x94\xa7\x20"
EMOJI_WRENCH_HAMMER="\xf0\x9f\x9b\xa0\x20\x20"
