#!/usr/bin/env bash

#===============================================================================================
# GLOBAL ENVIRONMENT VARIABLES
#===============================================================================================

# General
SETUP_MODE="FULL"  # DEFAULT: Full setup - installs everything in Brewfile and secondary
RUN_SECONDARY=false

# Setup Files
BREW_CASKS_FILE="./src/casks.txt"
BREW_FILE="./src/Brewfile"
BREW_FORMULAE_FILE="./src/formulae.txt"
BREW_TAPS_FILE="./src/taps.txt"
MAC_APPS_FILE="./src/apps.txt"

# Setup Configurations
GITHUB_KEYS_URL="https://github.com/settings/keys"
GITHUB_RSA_NAME="github_rsa"

# Color Outputs
GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
NC="\033[0m"

# Emojis UTF-8 Hex
EMOJI_CHECKMARK="\x20\xe2\x9c\x85\x20\x20"
EMOJI_ERROR="\x20\xe2\x9b\x94\xef\xb8\x8f\x20\x20"
EMOJI_FAIL="\x20\xe2\x9d\x8c\x20\x20"
EMOJI_GEAR="\x20\xe2\x9a\x99\xef\xb8\x8f\x20\x20"
EMOJI_INFO="\x20\xe2\x84\xb9\xef\xb8\x8f\x20\x20"
EMOJI_TRASH="\x20\xf0\x9f\x97\x91\x20\x20"
EMOJI_WARNING="\x20\xe2\x9b\x94\xef\xb8\x8f\x20\x20"
EMOJI_WRENCH="\x20\xf0\x9f\x94\xa7\x20\x20"

