# Application launcher and productivity software
cask "alfred"
# Web browser focusing on privacy
cask "brave-browser"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Web browser
cask "google-chrome"
# App to write, plan, collaborate, and get organised
cask "notion"
# Screenshot measurement and annotation tool
cask "shottr"
# Music streaming service
cask "spotify"
# Mac App Store Applications
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Blurred", id: 1497527363
mas "Calendar 366 II", id: 1265895169
mas "CloudMounter", id: 1130254674
mas "Commander One PRO", id: 1035237815
mas "Due", id: 524373870
mas "Hidden Bar", id: 1452453066
mas "Home Assistant", id: 1099568401
mas "Magnet", id: 441258766
mas "PayPal Honey", id: 1472777122
mas "RunCat", id: 1429033973
mas "ScreenBrush", id: 1233965871
mas "ScreenFloat", id: 414528154
mas "Slack", id: 803453959
mas "Snap", id: 418073146
mas "Snip", id: 1527428847
mas "Snippet", id: 1613020051
mas "Tot", id: 1491071483
mas "Trend Micro Ad Blocker", id: 1491889901
mas "Weather for Status Bar", id: 1448031908
mas "Yoink", id: 457622435
vscode "aaron-bond.better-comments"
vscode "adam-watters.vscode-color-pick"
vscode "adpyke.codesnap"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.bookmarks"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "andrew-codes.cypress-snippets"
vscode "azemoh.one-monokai"
vscode "be5invis.toml"
vscode "bierner.github-markdown-preview"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "budparr.language-hugo-vscode"
vscode "chakrounanas.turbo-console-log"
vscode "christian-kohler.path-intellisense"
vscode "cliffordfajardo.highlight-line-vscode"
vscode "crystal-spider.jsdoc-generator"
vscode "davidanson.vscode-markdownlint"
vscode "daylerees.rainglow"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "esbenp.prettier-vscode"
vscode "exodiusstudios.comment-anchors"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.auto-rename-tag"
vscode "foxundermoon.shell-format"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gruntfuggly.todo-tree"
vscode "gxl.git-graph-3"
vscode "humao.rest-client"
vscode "ibm.output-colorizer"
vscode "janne252.fontawesome-autocomplete"
vscode "jdinhlife.gruvbox"
vscode "jolaleye.horizon-theme-vscode"
vscode "kamikillerto.vscode-colorize"
vscode "kuscamara.electron"
vscode "mariusalchimavicius.json-to-ts"
vscode "mdickin.markdown-shortcuts"
vscode "gxl.git-graph-3"
vscode "mikemcbride.electron-highlighter"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-azuretools.vscode-containers"
vscode "docker.docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "mujichok.vscode-project-name-in-statusbar"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "pranaygp.vscode-css-peek"
vscode "pulumi.pulumi-lsp-client"
vscode "pulumi.pulumi-vscode-copilot"
vscode "pulumi.pulumi-vscode-tools"
vscode "rangav.vscode-thunder-client"
vscode "redhat.vscode-yaml"
vscode "remisa.shellman"
vscode "rid9.datetime"
vscode "royaction.color-manager"
vscode "snyk-security.snyk-vulnerability-scanner"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "taniarascia.new-moon-blue-vscode"
vscode "taniarascia.new-moon-vscode"
vscode "thenikso.github-plus-theme"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "tyriar.sort-lines"
vscode "vivaxy.vscode-conventional-commits"
vscode "vscode-icons-team.vscode-icons"
vscode "vsls-contrib.codetour"
vscode "wayou.vscode-todo-highlight"
vscode "weaveworks.vscode-gitops-tools"
vscode "wix.vscode-import-cost"
vscode "yzhang.markdown-all-in-one"
